Задание 1. Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.


In [14]:
import numpy as np

In [16]:
a = [[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]]
np_a = np.array(a)
np_a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [17]:
np_a.shape

(5, 2)

In [18]:
mean_a = np_a.mean(axis = 0)
mean_a

array([2. , 8.4])

Задание 2
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.


In [26]:
a_centered = np.subtract(np_a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3.
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.



In [27]:
a_centered_t = a_centered.T
a_centered_t
a_centered_sp = np.dot(a_centered_t[0], a_centered_t[1])
a_centered_sp

8.0

In [40]:
a_centered_sp/(np_a.shape[0] - 1)

2.0

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [41]:
np_a_t = np_a.T
np_a_t

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [42]:
np_a_cov = np.cov(np_a_t)
np_a_cov[0, 1]

2.0

In [35]:
a_centered_sp/(5 - 1) == np_a_cov[0, 1]

True